alert("Iremos fazer operações com 2 números")
let numberOne = prompt("Digite o primeiro número: ")
let numberTwo = prompt("Digite o segundo número: ")
alert("A soma dos Números é: " + (Number(numberOne) + Number(numberTwo)))
alert("A subtração dos Números é: " + (Number(numberOne) - Number(numberTwo)))
alert("A multiplicação dos Números é: " + (Number(numberOne) * Number(numberTwo)))
alert("A divisão dos Números é: " + (Number(numberOne) / Number(numberTwo)))
alert("O resto dos Números é: " + (Number(numberOne) % Number(numberTwo)))